name: network_entities
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  json_annotation: ^3.0.1

dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.3.1
  json_serializable: ^3.2.5
