name: san_router
description: A simple but powerful Flutter router.
version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.0
  pedantic: ^1.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
