name: Check and test api

on:
  pull_request:
    paths:
      - api/**
      - common/network_entities/**
      - .github/workflows/check_and_test_api.yaml
    branches:
      - master

jobs:
  check_and_test_api:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
        working-directory: ./api
      - name: Dart analyze
        run: dartanalyzer --options=analysis_options.yaml --fatal-hints --fatal-warnings .
        working-directory: ./api
      - name: Run tests
        run: pub run test
        working-directory: ./api
