name: Check and test san router

on:
  pull_request:
    paths:
      - packages/san_router/**
      - .github/workflows/check_and_test_san_router.yaml
    branches:
      - master

jobs:
  check_and_test_dashboard:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - name: "Get dependencies"
        run: flutter packages get
        working-directory: ./packages/san_router
      - name: "Check format"
        run: flutter format -n --set-exit-if-changed .
        working-directory: ./packages/san_router
      - name: "Flutter analyze"
        run: flutter analyze
        working-directory: ./packages/san_router
      - name: "Flutter test"
        run: flutter
        working-directory: ./packages/san_router
