name: Deploy staging pharmacy website

on:
  push:
    paths:
      - frontends/pharmacy_website/**
      - .github/workflows/deploy_pharmacy_website_staging.yaml
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo -u anyuser -p ${{secrets.SCALEWAY_TOKEN}}
      - name: Docker build
        run: docker build -f Dockerfile  -t stagingpw:latest .
        working-directory: ./frontends/pharmacy_website
      - name: Docker tag
        run: docker tag stagingpw:latest rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/stagingpw:latest
      - name: Docker push
        run: docker push rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/stagingpw:latest
      - name: Deploy container
        run: curl -X POST -H "X-Auth-Token:${{secrets.SCALEWAY_TOKEN}}" "https://api.scaleway.com/functions/v1alpha2/regions/fr-par/containers/1fd28bff-b38e-4429-a03c-4969f605be7e/deploy" -d "{}"
