name: Deploy staging accounts service

on:
  push:
    paths:
      - services/accounts/**
      - .github/workflows/deploy_accounts_service_staging.yaml
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo -u anyuser -p ${{secrets.SCALEWAY_TOKEN}}
      - name: Docker build
        run: docker build -f Dockerfile  -t stagingas:latest .
        working-directory: ./services/accounts
      - name: Docker tag
        run: docker tag stagingas:latest rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/stagingas:latest
      - name: Docker push
        run: docker push rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/stagingas:latest
      - name: Deploy container
        run: curl -X POST -H "X-Auth-Token:${{secrets.SCALEWAY_TOKEN}}" "https://api.scaleway.com/functions/v1alpha2/regions/fr-par/containers/b3649268-7437-49ec-8a4e-c932e2f9aea0/deploy" -d "{}"
